
import React from 'react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Share2, Download, Mail, MessageCircle } from 'lucide-react';
import { toast } from '@/components/ui/use-toast';
import { Invoice } from '@/context/InvoiceContext';

interface ShareInvoiceProps {
  invoice: Invoice;
  onDownloadPDF: () => void;
}

const ShareInvoice: React.FC<ShareInvoiceProps> = ({ invoice, onDownloadPDF }) => {
  const shareViaWhatsApp = () => {
    const message = `Invoice ${invoice.invoiceNo}\nBuyer: ${invoice.buyerName}\nTotal: ₹${invoice.totalAmount}\n\nGenerated by Agnee Gas Distributer`;
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  const shareViaEmail = () => {
    const subject = `Invoice ${invoice.invoiceNo} - ${invoice.buyerName}`;
    const body = `Dear ${invoice.buyerName},\n\nPlease find your invoice details below:\n\nInvoice Number: ${invoice.invoiceNo}\nDate: ${invoice.invoiceDate}\nTotal Amount: ₹${invoice.totalAmount}\n\nThank you for your business!\n\nBest regards,\nAgnee Gas Distributer`;
    const emailUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = emailUrl;
  };

  const shareViaWebShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Invoice ${invoice.invoiceNo}`,
          text: `Invoice for ${invoice.buyerName} - Total: ₹${invoice.totalAmount}`,
          url: window.location.href,
        });
      } catch (error) {
        console.error('Error sharing:', error);
        toast({
          title: 'Share Failed',
          description: 'Unable to share. Please try another method.',
          variant: 'destructive',
        });
      }
    } else {
      toast({
        title: 'Share Not Supported',
        description: 'Web sharing is not supported on this device.',
        variant: 'destructive',
      });
    }
  };

  const copyToClipboard = () => {
    const invoiceText = `Invoice ${invoice.invoiceNo}\nBuyer: ${invoice.buyerName}\nDate: ${invoice.invoiceDate}\nTotal: ₹${invoice.totalAmount}\n\nGenerated by Agnee Gas Distributer`;
    navigator.clipboard.writeText(invoiceText).then(() => {
      toast({
        title: 'Copied!',
        description: 'Invoice details copied to clipboard.',
      });
    }).catch(() => {
      toast({
        title: 'Copy Failed',
        description: 'Unable to copy to clipboard.',
        variant: 'destructive',
      });
    });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          <Share2 className="h-4 w-4" />
          Share
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuItem onClick={onDownloadPDF}>
          <Download className="h-4 w-4 mr-2" />
          Download PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={shareViaWhatsApp}>
          <MessageCircle className="h-4 w-4 mr-2" />
          Share via WhatsApp
        </DropdownMenuItem>
        <DropdownMenuItem onClick={shareViaEmail}>
          <Mail className="h-4 w-4 mr-2" />
          Share via Email
        </DropdownMenuItem>
        <DropdownMenuItem onClick={shareViaWebShare}>
          <Share2 className="h-4 w-4 mr-2" />
          Share via Apps
        </DropdownMenuItem>
        <DropdownMenuItem onClick={copyToClipboard}>
          <Share2 className="h-4 w-4 mr-2" />
          Copy Details
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ShareInvoice;
