// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duitlzyadcfmlgvnryxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aXRsenlhZGNmbWxndm5yeXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDMyNjUsImV4cCI6MjA2MzkxOTI2NX0.Cxb8xA0fD8Gk0Mlx4uDpmwHdYnuu5XQurtP5Cy-Z7SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);